class CreateUserError(Exception):
    pass


class UserNotFound(Exception):
    pass